
/**************************************************************
 *	
 *	bgMusic, 8 bit, 11025Hz,
 *	1 channel, 1214976 bytes/channel
 *	Total Size: 1 * 1214976 + 4 (header) = 1215020 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\kimbe\Documents\CS2261\FinalProject\M04\bgMusic.wav
 *	Time-stamp: Tue Nov 26 18:21:44 2019
 *	
 **************************************************************/

#ifndef __BGMUSICH__
#define __BGMUSICH__

#define BGMUSICFREQ 11025
#define BGMUSICLEN 1214976

extern const unsigned char bgMusic[1214976];

#endif /* __BGMUSICH__ */
