
/**************************************************************
 *	
 *	oof, 8 bit, 11025Hz,
 *	1 channel, 12389 bytes/channel
 *	Total Size: 1 * 12389 + 4 (header) = 12433 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\kimbe\Documents\CS2261\FinalProject\M05\oof.wav
 *	Time-stamp: Thu Dec 05 22:33:00 2019
 *	
 **************************************************************/

#ifndef __OOFH__
#define __OOFH__

#define OOFFREQ 11025
#define OOFLEN 12389

extern const unsigned char oof[12389];

#endif /* __OOFH__ */
