
/**************************************************************
 *	
 *	startScreenMusic, 8 bit, 11025Hz,
 *	1 channel, 1029888 bytes/channel
 *	Total Size: 1 * 1029888 + 4 (header) = 1029932 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\kimbe\Documents\CS2261\FinalProject\M04\startScreenMusic.wav
 *	Time-stamp: Tue Nov 26 18:21:57 2019
 *	
 **************************************************************/

#ifndef __STARTSCREENMUSICH__
#define __STARTSCREENMUSICH__

#define STARTSCREENMUSICFREQ 11025
#define STARTSCREENMUSICLEN 1029888

extern const unsigned char startScreenMusic[1029888];

#endif /* __STARTSCREENMUSICH__ */
