
/**************************************************************
 *	
 *	transition, 8 bit, 11025Hz,
 *	1 channel, 10678 bytes/channel
 *	Total Size: 1 * 10678 + 4 (header) = 10722 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\kimbe\Documents\CS2261\FinalProject\M05\transition.wav
 *	Time-stamp: Fri Dec 06 11:51:01 2019
 *	
 **************************************************************/

#ifndef __TRANSITIONH__
#define __TRANSITIONH__

#define TRANSITIONFREQ 11025
#define TRANSITIONLEN 10678

extern const unsigned char transition[10678];

#endif /* __TRANSITIONH__ */
