
/**************************************************************
 *	
 *	victory, 8 bit, 11025Hz,
 *	1 channel, 184174 bytes/channel
 *	Total Size: 1 * 184174 + 4 (header) = 184218 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\kimbe\Documents\CS2261\FinalProject\M05\victory.wav
 *	Time-stamp: Fri Dec 06 11:40:41 2019
 *	
 **************************************************************/

#ifndef __VICTORYH__
#define __VICTORYH__

#define VICTORYFREQ 11025
#define VICTORYLEN 184174

extern const unsigned char victory[184174];

#endif /* __VICTORYH__ */
